//! Disinfo analysis report export (Sprint D6).
//!
//! Generates a comprehensive Markdown report summarizing disinformation
//! analysis results for a narrative. Includes entity summary, situation
//! timeline, spread statistics, and CIB indicators.

use crate::error::Result;
use crate::hypergraph::Hypergraph;
use crate::types::EntityType;

use super::{
    collect_narrative_data, entity_display_name, situation_preview, sort_situations_by_time,
};

/// Generate a Markdown disinfo analysis report for a narrative.
pub fn export_disinfo_report(hypergraph: &Hypergraph, narrative_id: &str) -> Result<String> {
    let data = collect_narrative_data(narrative_id, hypergraph)?;

    let mut md = String::new();

    // Title
    md.push_str(&format!(
        "# Disinformation Analysis Report: {}\n\n",
        narrative_id
    ));
    md.push_str(&format!(
        "Generated: {}\n\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));

    // Executive summary
    md.push_str("## Executive Summary\n\n");
    md.push_str(&format!(
        "- **Entities**: {} ({} actors, {} locations, {} organizations)\n",
        data.entities.len(),
        data.entities
            .iter()
            .filter(|e| e.entity_type == EntityType::Actor)
            .count(),
        data.entities
            .iter()
            .filter(|e| e.entity_type == EntityType::Location)
            .count(),
        data.entities
            .iter()
            .filter(|e| e.entity_type == EntityType::Organization)
            .count(),
    ));
    md.push_str(&format!("- **Situations**: {}\n", data.situations.len()));
    md.push_str(&format!(
        "- **Causal Links**: {}\n",
        data.causal_links.len()
    ));
    md.push_str(&format!(
        "- **Participations**: {}\n\n",
        data.participations.len()
    ));

    // Actors table
    let actors: Vec<_> = data
        .entities
        .iter()
        .filter(|e| e.entity_type == EntityType::Actor)
        .collect();
    if !actors.is_empty() {
        md.push_str("## Actors\n\n");
        md.push_str("| Name | Confidence | Platform | Maturity |\n");
        md.push_str("|------|-----------|----------|----------|\n");
        for actor in &actors {
            let name = entity_display_name(actor, "(unnamed)");
            let platform = actor
                .properties
                .get("platform")
                .and_then(|v| v.as_str())
                .unwrap_or("-");
            md.push_str(&format!(
                "| {} | {:.2} | {} | {:?} |\n",
                name, actor.confidence, platform, actor.maturity
            ));
        }
        md.push('\n');
    }

    // Timeline
    if !data.situations.is_empty() {
        md.push_str("## Timeline\n\n");
        let sorted = sort_situations_by_time(&data.situations);
        for sit in &sorted {
            let time = sit
                .temporal
                .start
                .map(|t| t.format("%Y-%m-%d %H:%M").to_string())
                .unwrap_or_else(|| "unknown".to_string());
            let preview = situation_preview(sit, 120, || format!("[situation {}]", sit.id));
            md.push_str(&format!(
                "- **{}** (conf: {:.2}): {}\n",
                time, sit.confidence, preview
            ));
        }
        md.push('\n');
    }

    // Network overview
    if !data.participations.is_empty() {
        md.push_str("## Network Overview\n\n");

        // Count participations per actor
        let mut actor_counts: std::collections::HashMap<uuid::Uuid, usize> =
            std::collections::HashMap::new();
        for p in &data.participations {
            *actor_counts.entry(p.entity_id).or_insert(0) += 1;
        }

        // Sort by count descending and show top 10
        let mut sorted_actors: Vec<_> = actor_counts.into_iter().collect();
        sorted_actors.sort_by(|a, b| b.1.cmp(&a.1));

        md.push_str("| Actor | Participation Count |\n");
        md.push_str("|-------|--------------------|\n");
        for (entity_id, count) in sorted_actors.iter().take(10) {
            let name = data
                .entities
                .iter()
                .find(|e| e.id == *entity_id)
                .map(|e| entity_display_name(e, "(unnamed)"))
                .unwrap_or("(unknown)");
            md.push_str(&format!("| {} | {} |\n", name, count));
        }
        md.push('\n');
    }

    // Causal chains
    if !data.causal_links.is_empty() {
        md.push_str("## Causal Chain Summary\n\n");
        md.push_str(&format!(
            "{} causal links detected across {} situations.\n\n",
            data.causal_links.len(),
            data.situations.len()
        ));
    }

    // Methodology note
    md.push_str("---\n\n");
    md.push_str("*Report generated by TENSA Disinfo Analysis Engine (Sprint D6).*\n");

    Ok(md)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::memory::MemoryStore;
    use std::sync::Arc;

    #[test]
    fn test_export_disinfo_report_empty() {
        let store = Arc::new(MemoryStore::new());
        let hg = Hypergraph::new(store);
        let report = export_disinfo_report(&hg, "empty-nar").unwrap();
        assert!(report.contains("Disinformation Analysis Report: empty-nar"));
        assert!(report.contains("Entities**: 0"));
    }

    #[test]
    fn test_export_disinfo_report_with_data() {
        use crate::types::*;
        use chrono::Utc;
        use uuid::Uuid;

        let store = Arc::new(MemoryStore::new());
        let hg = Hypergraph::new(store);

        let entity = Entity {
            id: Uuid::now_v7(),
            entity_type: EntityType::Actor,
            properties: serde_json::json!({"name": "TrollBot", "platform": "telegram"}),
            beliefs: None,
            embedding: None,
            narrative_id: Some("report-test".to_string()),
            maturity: MaturityLevel::Candidate,
            confidence: 0.7,
            confidence_breakdown: None,
            extraction_method: None,
            provenance: vec![],
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
            transaction_time: None,
        };
        hg.create_entity(entity).unwrap();

        let report = export_disinfo_report(&hg, "report-test").unwrap();
        assert!(report.contains("TrollBot"));
        assert!(report.contains("telegram"));
        assert!(report.contains("Actors"));
    }
}
