//! Report export — generates a structured analytical report from narrative data.
//!
//! Produces a Markdown document with timeline, entity profiles, relationship
//! co-occurrence matrix, and causal chain summaries.

use std::collections::HashMap;

use uuid::Uuid;

use crate::error::Result;
use crate::export::{
    entity_display_name, situation_preview, sort_situations_by_time, NarrativeExport,
};
use crate::types::{Entity, Participation, Role, Situation};

/// Export narrative data as a Markdown analytical report.
pub fn export_report(data: &NarrativeExport) -> Result<String> {
    let mut out =
        String::with_capacity(data.situations.len() * 150 + data.participations.len() * 60 + 1024);

    out.push_str(&format!("# Narrative Report: {}\n\n", data.narrative_id));

    let sorted_situations = sort_situations_by_time(&data.situations);
    let entity_map: HashMap<Uuid, &Entity> = data.entities.iter().map(|e| (e.id, e)).collect();
    let sit_map: HashMap<Uuid, &Situation> = data.situations.iter().map(|s| (s.id, s)).collect();

    // Pre-compute participation indexes (used by both profiles and relationships)
    let mut entity_parts: HashMap<Uuid, Vec<&Participation>> = HashMap::new();
    let mut sit_entities: HashMap<Uuid, Vec<Uuid>> = HashMap::new();
    for p in &data.participations {
        entity_parts.entry(p.entity_id).or_default().push(p);
        sit_entities
            .entry(p.situation_id)
            .or_default()
            .push(p.entity_id);
    }

    out.push_str(&render_timeline(&sorted_situations));
    out.push_str(&render_entity_profiles(&data.entities, &entity_parts));
    out.push_str(&render_relationships(
        &data.entities,
        &sit_entities,
        &entity_map,
    ));
    out.push_str(&render_causal_chains(&data.causal_links, &sit_map));

    out.push_str("---\n*Generated by TENSA*\n");
    Ok(out)
}

/// Render the timeline section as a Markdown table.
fn render_timeline(situations: &[&Situation]) -> String {
    let mut out = String::from("## Timeline\n\n");

    if situations.is_empty() {
        out.push_str("*No events recorded.*\n\n");
        return out;
    }

    out.push_str("| # | Timestamp | Level | Description |\n");
    out.push_str("|---|-----------|-------|-------------|\n");

    for (i, sit) in situations.iter().enumerate() {
        let ts = sit
            .temporal
            .start
            .map(|t| t.format("%Y-%m-%d %H:%M").to_string())
            .unwrap_or_else(|| "unknown".into());
        let level = sit.narrative_level.as_index_str();
        let desc = situation_description(sit);
        out.push_str(&format!("| {} | {} | {} | {} |\n", i + 1, ts, level, desc));
    }
    out.push('\n');
    out
}

/// Render entity profiles with participation counts, roles, and key actions.
fn render_entity_profiles(
    entities: &[Entity],
    entity_parts: &HashMap<Uuid, Vec<&Participation>>,
) -> String {
    let mut out = String::from("## Entity Profiles\n\n");

    if entities.is_empty() {
        out.push_str("*No entities in this narrative.*\n\n");
        return out;
    }

    for entity in entities {
        let name = entity_display_name(entity, "Unknown");
        let etype = format!("{:?}", entity.entity_type);
        out.push_str(&format!("### {} ({})\n\n", name, etype));

        let parts = entity_parts.get(&entity.id);
        let count = parts.map_or(0, |v| v.len());
        out.push_str(&format!("- **Participations:** {}\n", count));

        if let Some(parts) = parts {
            // Role breakdown
            let mut role_counts: HashMap<String, usize> = HashMap::new();
            let mut actions: Vec<&str> = Vec::new();
            for p in parts {
                *role_counts.entry(role_label(&p.role)).or_default() += 1;
                if let Some(ref a) = p.action {
                    if !a.is_empty() {
                        actions.push(a.as_str());
                    }
                }
            }
            let roles: Vec<String> = role_counts
                .iter()
                .map(|(r, c)| format!("{} ({})", r, c))
                .collect();
            if !roles.is_empty() {
                out.push_str(&format!("- **Roles:** {}\n", roles.join(", ")));
            }
            if !actions.is_empty() {
                actions.truncate(5); // top 5
                out.push_str(&format!("- **Key actions:** {}\n", actions.join(", ")));
            }
        }

        out.push_str(&format!("- **Confidence:** {:.2}\n\n", entity.confidence));
    }

    out
}

/// Render relationship co-occurrence matrix.
fn render_relationships(
    entities: &[Entity],
    sit_entities: &HashMap<Uuid, Vec<Uuid>>,
    entity_map: &HashMap<Uuid, &Entity>,
) -> String {
    let mut out = String::from("## Relationships\n\n");

    if entities.len() < 2 {
        out.push_str("*Not enough entities for relationship analysis.*\n\n");
        return out;
    }

    // Count co-occurrences for each entity pair
    let mut cooccurrences: HashMap<(Uuid, Uuid), usize> = HashMap::new();
    for entities_in_sit in sit_entities.values() {
        for (i, &a) in entities_in_sit.iter().enumerate() {
            for &b in &entities_in_sit[i + 1..] {
                let key = if a < b { (a, b) } else { (b, a) };
                *cooccurrences.entry(key).or_default() += 1;
            }
        }
    }

    if cooccurrences.is_empty() {
        out.push_str("*No co-occurrences detected.*\n\n");
        return out;
    }

    // Sort by count descending
    let mut pairs: Vec<_> = cooccurrences.into_iter().collect();
    pairs.sort_by(|a, b| b.1.cmp(&a.1));

    out.push_str("| Entity A | Entity B | Co-occurrences |\n");
    out.push_str("|----------|----------|----------------|\n");

    for ((a, b), count) in &pairs {
        let name_a = entity_map
            .get(a)
            .map_or("?", |e| entity_display_name(e, "?"));
        let name_b = entity_map
            .get(b)
            .map_or("?", |e| entity_display_name(e, "?"));
        out.push_str(&format!("| {} | {} | {} |\n", name_a, name_b, count));
    }
    out.push('\n');
    out
}

/// Render causal chain summary.
fn render_causal_chains(
    causal_links: &[crate::types::CausalLink],
    sit_map: &HashMap<Uuid, &Situation>,
) -> String {
    let mut out = String::from("## Causal Chains\n\n");

    if causal_links.is_empty() {
        out.push_str("*No causal links recorded.*\n\n");
        return out;
    }

    for link in causal_links {
        let from_desc = sit_map
            .get(&link.from_situation)
            .map(|s| situation_description(s))
            .unwrap_or_else(|| link.from_situation.to_string());
        let to_desc = sit_map
            .get(&link.to_situation)
            .map(|s| situation_description(s))
            .unwrap_or_else(|| link.to_situation.to_string());
        out.push_str(&format!(
            "- [{}] --{:?}--> [{}] (strength: {:.2})\n",
            from_desc, link.causal_type, to_desc, link.strength
        ));
    }
    out.push('\n');
    out
}

/// Extract a short description from a situation's raw_content.
fn situation_description(sit: &Situation) -> String {
    situation_preview(sit, 77, || {
        format!("Situation {}", &sit.id.to_string()[..8])
    })
}

/// Display label for a Role.
fn role_label(role: &Role) -> String {
    match role {
        Role::Custom(s) => s.clone(),
        other => format!("{:?}", other),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::*;
    use chrono::{TimeZone, Utc};
    use uuid::Uuid;

    fn make_entity(name: &str, etype: EntityType) -> Entity {
        Entity {
            id: Uuid::now_v7(),
            entity_type: etype,
            properties: serde_json::json!({"name": name}),
            beliefs: None,
            embedding: None,
            maturity: MaturityLevel::Candidate,
            confidence: 0.9,
            confidence_breakdown: None,
            provenance: vec![],
            extraction_method: None,
            narrative_id: Some("test".into()),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
            transaction_time: None,
        }
    }

    fn make_situation_with_time(desc: &str, start: Option<chrono::DateTime<Utc>>) -> Situation {
        Situation {
            id: Uuid::now_v7(),
            properties: serde_json::Value::Null,
            name: None,
            description: None,
            temporal: AllenInterval {
                start,
                end: None,
                granularity: TimeGranularity::Approximate,
                relations: vec![],
                fuzzy_endpoints: None,
            },
            spatial: None,
            game_structure: None,
            causes: vec![],
            deterministic: None,
            probabilistic: None,
            embedding: None,
            raw_content: vec![ContentBlock::text(desc)],
            narrative_level: NarrativeLevel::Scene,
            discourse: None,
            maturity: MaturityLevel::Candidate,
            confidence: 0.8,
            confidence_breakdown: None,
            extraction_method: ExtractionMethod::LlmParsed,
            provenance: vec![],
            narrative_id: Some("test".into()),
            source_chunk_id: None,
            source_span: None,
            synopsis: None,
            manuscript_order: None,
            parent_situation_id: None,
            label: None,
            status: None,
            keywords: vec![],
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
            transaction_time: None,
        }
    }

    fn make_export(
        entities: Vec<Entity>,
        situations: Vec<Situation>,
        participations: Vec<Participation>,
        causal_links: Vec<CausalLink>,
    ) -> NarrativeExport {
        NarrativeExport {
            narrative_id: "test-report".into(),
            entities,
            situations,
            participations,
            causal_links,
        }
    }

    #[test]
    fn test_report_empty_narrative() {
        let data = make_export(vec![], vec![], vec![], vec![]);
        let md = export_report(&data).unwrap();
        assert!(md.contains("# Narrative Report: test-report"));
        assert!(md.contains("No events recorded"));
        assert!(md.contains("No entities"));
    }

    #[test]
    fn test_report_timeline_ordering() {
        let t1 = Utc.with_ymd_and_hms(2024, 1, 1, 12, 0, 0).unwrap();
        let t2 = Utc.with_ymd_and_hms(2024, 6, 1, 12, 0, 0).unwrap();
        let s1 = make_situation_with_time("First", Some(t1));
        let s2 = make_situation_with_time("Second", Some(t2));
        let data = make_export(vec![], vec![s2, s1], vec![], vec![]);
        let md = export_report(&data).unwrap();
        let pos_first = md.find("First").unwrap();
        let pos_second = md.find("Second").unwrap();
        assert!(pos_first < pos_second);
    }

    #[test]
    fn test_report_entity_profiles() {
        let alice = make_entity("Alice", EntityType::Actor);
        let data = make_export(vec![alice], vec![], vec![], vec![]);
        let md = export_report(&data).unwrap();
        assert!(md.contains("### Alice (Actor)"));
        assert!(md.contains("**Participations:** 0"));
    }

    #[test]
    fn test_report_relationships() {
        let alice = make_entity("Alice", EntityType::Actor);
        let bob = make_entity("Bob", EntityType::Actor);
        let sit = make_situation_with_time("Meeting", None);

        let p1 = Participation {
            entity_id: alice.id,
            situation_id: sit.id,
            role: Role::Protagonist,
            info_set: None,
            action: Some("speaks".into()),
            payoff: None,
            seq: 0,
        };
        let p2 = Participation {
            entity_id: bob.id,
            situation_id: sit.id,
            role: Role::Witness,
            info_set: None,
            action: None,
            payoff: None,
            seq: 0,
        };

        let data = make_export(vec![alice, bob], vec![sit], vec![p1, p2], vec![]);
        let md = export_report(&data).unwrap();
        assert!(md.contains("Alice"));
        assert!(md.contains("Bob"));
        assert!(md.contains("Co-occurrences"));
        assert!(md.contains("| 1 |"));
    }

    #[test]
    fn test_report_causal_chains() {
        let s1 = make_situation_with_time("The argument", None);
        let s2 = make_situation_with_time("The departure", None);

        let link = CausalLink {
            from_situation: s1.id,
            to_situation: s2.id,
            mechanism: Some("escalation".into()),
            strength: 0.85,
            causal_type: CausalType::Necessary,
            maturity: MaturityLevel::Candidate,
        };

        let data = make_export(vec![], vec![s1, s2], vec![], vec![link]);
        let md = export_report(&data).unwrap();
        assert!(md.contains("The argument"));
        assert!(md.contains("The departure"));
        assert!(md.contains("Necessary"));
        assert!(md.contains("0.85"));
    }

    #[test]
    fn test_report_participation_roles() {
        let alice = make_entity("Alice", EntityType::Actor);
        let s1 = make_situation_with_time("Event 1", None);
        let s2 = make_situation_with_time("Event 2", None);

        let p1 = Participation {
            entity_id: alice.id,
            situation_id: s1.id,
            role: Role::Protagonist,
            info_set: None,
            action: Some("confronts".into()),
            payoff: None,
            seq: 0,
        };
        let p2 = Participation {
            entity_id: alice.id,
            situation_id: s2.id,
            role: Role::Witness,
            info_set: None,
            action: Some("observes".into()),
            payoff: None,
            seq: 0,
        };

        let data = make_export(vec![alice], vec![s1, s2], vec![p1, p2], vec![]);
        let md = export_report(&data).unwrap();
        assert!(md.contains("**Participations:** 2"));
        assert!(md.contains("Protagonist"));
        assert!(md.contains("Witness"));
        assert!(md.contains("confronts"));
    }

    #[test]
    fn test_report_multiple_entities_situations() {
        let alice = make_entity("Alice", EntityType::Actor);
        let bob = make_entity("Bob", EntityType::Actor);
        let loc = make_entity("Cafe", EntityType::Location);

        let t1 = Utc.with_ymd_and_hms(2024, 3, 1, 10, 0, 0).unwrap();
        let t2 = Utc.with_ymd_and_hms(2024, 3, 1, 14, 0, 0).unwrap();
        let s1 = make_situation_with_time("Morning meeting", Some(t1));
        let s2 = make_situation_with_time("Afternoon follow-up", Some(t2));

        let parts = vec![
            Participation {
                entity_id: alice.id,
                situation_id: s1.id,
                role: Role::Protagonist,
                info_set: None,
                action: None,
                payoff: None,
                seq: 0,
            },
            Participation {
                entity_id: bob.id,
                situation_id: s1.id,
                role: Role::Antagonist,
                info_set: None,
                action: None,
                payoff: None,
                seq: 0,
            },
        ];

        let data = make_export(vec![alice, bob, loc], vec![s1, s2], parts, vec![]);
        let md = export_report(&data).unwrap();
        assert!(md.contains("Morning meeting"));
        assert!(md.contains("Afternoon follow-up"));
        assert!(md.contains("Alice"));
        assert!(md.contains("Bob"));
        assert!(md.contains("Cafe"));
    }

    #[test]
    fn test_report_no_causal_links() {
        let s1 = make_situation_with_time("Something", None);
        let data = make_export(vec![], vec![s1], vec![], vec![]);
        let md = export_report(&data).unwrap();
        assert!(md.contains("## Causal Chains"));
        assert!(md.contains("No causal links recorded"));
    }
}
