//! Bootstrap confidence intervals and calibrated p-values for stylometry.
//!
//! Replaces hard-coded thresholds (e.g., the legacy 0.7 anomaly gate) with
//! statistically principled measures derived from the empirical distribution
//! of chunk-level similarities in the data itself.
//!
//! Two main capabilities:
//! - **Per-chunk anomaly p-values** — resample chunks with replacement to build
//!   a null distribution of "same-author" chunk-to-global similarities, then
//!   report each observed chunk's empirical left-tail p-value.
//! - **Narrative-pair similarity CIs** — percentile confidence intervals for
//!   the weighted overall fingerprint similarity between two narratives, plus
//!   per-layer CIs.
//!
//! All randomness goes through a seeded `ChaCha8Rng` for reproducibility.

use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha8Rng;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use crate::analysis::style_profile::{
    fingerprint_similarity_weighted, prose_similarity_weighted, NarrativeFingerprint,
    StyleSimilarity, WeightedSimilarityConfig,
};
use crate::analysis::stylometry::{aggregate_features, ProseStyleFeatures};

/// Default number of bootstrap iterations when the caller does not specify.
pub const DEFAULT_BOOTSTRAP_ITER: usize = 1000;

/// Default significance level used when converting similarity thresholds to p-values.
pub const DEFAULT_ALPHA: f32 = 0.05;

// ─── Types ──────────────────────────────────────────────────

/// Empirical null distribution of chunk-vs-global prose similarities under
/// the "same author" hypothesis. Built by bootstrap resampling.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BootstrapNull {
    pub similarities: Vec<f32>,
    pub mean: f32,
    pub std: f32,
    pub n_iter: usize,
    pub seed: u64,
}

/// Percentile confidence interval for a single similarity statistic.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimilarityCi {
    pub estimate: f32,
    pub ci_low: f32,
    pub ci_high: f32,
    pub alpha: f32,
    pub n_iter: usize,
    /// Tag indicating whether this CI reflects true resampling or a point estimate
    /// (when a layer cannot be resampled because chunks are unavailable).
    #[serde(default)]
    pub resample_source: String,
}

impl SimilarityCi {
    /// Construct a degenerate CI where low == high == estimate (used for layers
    /// that don't support bootstrap resampling).
    pub fn point(estimate: f32) -> Self {
        Self {
            estimate,
            ci_low: estimate,
            ci_high: estimate,
            alpha: 0.0,
            n_iter: 0,
            resample_source: "point".into(),
        }
    }
}

/// Confidence-interval-augmented narrative-pair similarity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StyleSimilarityCi {
    pub estimate: StyleSimilarity,
    pub overall: SimilarityCi,
    pub per_layer: HashMap<String, SimilarityCi>,
    pub n_iter: usize,
    pub alpha: f32,
    pub seed: u64,
}

/// Per-chunk anomaly result with calibrated p-value.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnomalyPValue {
    pub chunk_index: usize,
    pub observed_similarity: f32,
    pub p_value: f32,
    pub null_mean: f32,
    pub null_std: f32,
    pub flagged: bool,
    pub most_deviant_features: Vec<(String, f32)>,
}

// ─── Bootstrap null distribution (per-chunk anomaly) ────────

/// Build the null distribution of chunk-vs-synthetic-global similarities under
/// the assumption that chunks are exchangeable (= same author).
///
/// For each of `n_iter` iterations:
/// 1. Resample `chunks.len()` chunks with replacement.
/// 2. Aggregate them into a synthetic global profile.
/// 3. Pick a chunk uniformly at random and compute its prose similarity
///    against that synthetic global.
///
/// The result approximates the distribution of similarities we would see if
/// every chunk were generated by the same author as the aggregate — chunks
/// whose observed similarity falls deep in the left tail are anomalous.
pub fn bootstrap_null_chunk_similarity(
    chunks: &[ProseStyleFeatures],
    n_iter: usize,
    cfg: &WeightedSimilarityConfig,
    seed: u64,
) -> BootstrapNull {
    if chunks.is_empty() || n_iter == 0 {
        return BootstrapNull {
            similarities: vec![],
            mean: 0.0,
            std: 0.0,
            n_iter,
            seed,
        };
    }
    let mut rng = ChaCha8Rng::seed_from_u64(seed);
    let mut sims = Vec::with_capacity(n_iter);
    let n = chunks.len();
    let mut sample_buf: Vec<ProseStyleFeatures> = Vec::with_capacity(n);

    for _ in 0..n_iter {
        sample_buf.clear();
        for _ in 0..n {
            let idx = rng.gen_range(0..n);
            sample_buf.push(chunks[idx].clone());
        }
        let global = aggregate_features(&sample_buf);
        let pick = rng.gen_range(0..n);
        let sim = prose_similarity_weighted(&global, &chunks[pick], cfg);
        sims.push(sim);
    }

    let mean = sims.iter().sum::<f32>() / sims.len() as f32;
    let var = sims.iter().map(|s| (s - mean).powi(2)).sum::<f32>() / sims.len() as f32;
    BootstrapNull {
        similarities: sims,
        mean,
        std: var.sqrt(),
        n_iter,
        seed,
    }
}

/// Empirical left-tail p-value for an observed similarity under the null.
///
/// Returns `(count of null samples ≤ observed) / n`. Lower observed similarity
/// ⇒ lower p-value ⇒ more significant evidence of anomaly.
pub fn calibrated_anomaly_p_value(observed: f32, null: &BootstrapNull) -> f32 {
    if null.similarities.is_empty() {
        return 1.0;
    }
    let n = null.similarities.len() as f32;
    let count = null.similarities.iter().filter(|&&s| s <= observed).count() as f32;
    count / n
}

/// Detect per-chunk style anomalies using calibrated bootstrap p-values.
///
/// For each chunk, compute the observed prose similarity against the full-corpus
/// global, then compare against the bootstrap null distribution. Flag chunks
/// whose p-value is below `alpha`.
pub fn detect_style_anomalies_calibrated(
    chunks: &[ProseStyleFeatures],
    alpha: f32,
    n_iter: usize,
    cfg: &WeightedSimilarityConfig,
    seed: u64,
) -> Vec<AnomalyPValue> {
    if chunks.is_empty() {
        return vec![];
    }
    let global = aggregate_features(chunks);
    let null = bootstrap_null_chunk_similarity(chunks, n_iter, cfg, seed);

    chunks
        .iter()
        .enumerate()
        .map(|(i, chunk)| {
            let observed = prose_similarity_weighted(&global, chunk, cfg);
            let p = calibrated_anomaly_p_value(observed, &null);
            let mut deviant = vec![
                (
                    "avg_sentence_length".into(),
                    (chunk.avg_sentence_length - global.avg_sentence_length).abs(),
                ),
                (
                    "sentence_length_std".into(),
                    (chunk.sentence_length_std - global.sentence_length_std).abs(),
                ),
                (
                    "avg_word_length".into(),
                    (chunk.avg_word_length - global.avg_word_length).abs(),
                ),
                (
                    "type_token_ratio".into(),
                    (chunk.type_token_ratio - global.type_token_ratio).abs(),
                ),
                (
                    "dialogue_ratio".into(),
                    (chunk.dialogue_ratio - global.dialogue_ratio).abs(),
                ),
                (
                    "flesch_kincaid_grade".into(),
                    (chunk.flesch_kincaid_grade - global.flesch_kincaid_grade).abs(),
                ),
                (
                    "passive_voice_ratio".into(),
                    (chunk.passive_voice_ratio - global.passive_voice_ratio).abs(),
                ),
            ];
            deviant.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
            deviant.truncate(5);
            AnomalyPValue {
                chunk_index: i,
                observed_similarity: observed,
                p_value: p,
                null_mean: null.mean,
                null_std: null.std,
                flagged: p < alpha,
                most_deviant_features: deviant,
            }
        })
        .collect()
}

// ─── Narrative-pair similarity CI ───────────────────────────

/// Resample the prose layer of a fingerprint from a pool of chunk-level features.
fn resample_prose(chunks: &[ProseStyleFeatures], rng: &mut ChaCha8Rng) -> ProseStyleFeatures {
    let n = chunks.len();
    if n == 0 {
        return aggregate_features(&[]);
    }
    let mut sample: Vec<ProseStyleFeatures> = Vec::with_capacity(n);
    for _ in 0..n {
        let idx = rng.gen_range(0..n);
        sample.push(chunks[idx].clone());
    }
    aggregate_features(&sample)
}

/// Bootstrap CIs for the weighted narrative-pair similarity.
///
/// Only the prose layer is resampled; structural layers use the point estimate
/// from the pre-computed fingerprints (see the plan's `bootstrap_structural`
/// extension point — currently not enabled due to cost). Each structural layer's
/// CI is reported with `resample_source = "point"` so downstream consumers can
/// distinguish resampled uncertainty from static values.
#[allow(clippy::too_many_arguments)]
pub fn bootstrap_pair_similarity_ci(
    fp_a: &NarrativeFingerprint,
    fp_b: &NarrativeFingerprint,
    chunks_a: &[ProseStyleFeatures],
    chunks_b: &[ProseStyleFeatures],
    cfg: &WeightedSimilarityConfig,
    alpha: f32,
    n_iter: usize,
    seed: u64,
) -> StyleSimilarityCi {
    let point = fingerprint_similarity_weighted(fp_a, fp_b, cfg);

    if chunks_a.is_empty() || chunks_b.is_empty() || n_iter == 0 {
        return StyleSimilarityCi {
            overall: SimilarityCi::point(point.overall),
            per_layer: layer_ci_map_point(&point),
            estimate: point,
            n_iter,
            alpha,
            seed,
        };
    }

    let mut rng = ChaCha8Rng::seed_from_u64(seed);
    let mut overalls = Vec::with_capacity(n_iter);
    let mut prose_vals = Vec::with_capacity(n_iter);

    for _ in 0..n_iter {
        let prose_a = resample_prose(chunks_a, &mut rng);
        let prose_b = resample_prose(chunks_b, &mut rng);
        let sim = prose_similarity_weighted(&prose_a, &prose_b, cfg);
        // Recompose overall using the resampled prose + point-estimate structural layers.
        // Weights follow the same scheme as fingerprint_similarity_weighted.
        let w_prose = cfg.w_prose_fw.max(cfg.w_prose_scalars).max(0.0);
        let pairs = [
            (w_prose, sim),
            (cfg.w_rhythm.max(0.0), point.rhythm_similarity),
            (
                cfg.w_character.max(0.0),
                point.character_dynamics_similarity,
            ),
            (cfg.w_info.max(0.0), point.information_flow_similarity),
            (cfg.w_causal.max(0.0), point.causal_similarity),
            (cfg.w_temporal.max(0.0), point.temporal_similarity),
            (cfg.w_topology.max(0.0), point.topology_similarity),
        ];
        let denom: f32 = pairs.iter().map(|(w, _)| *w).sum();
        let overall = if denom <= 1e-6 {
            pairs.iter().map(|(_, v)| *v).sum::<f32>() / pairs.len() as f32
        } else {
            pairs.iter().map(|(w, v)| w * v).sum::<f32>() / denom
        };
        overalls.push(overall);
        prose_vals.push(sim);
    }

    let overall_ci = percentile_ci(&mut overalls, point.overall, alpha, n_iter, "bootstrap");
    let prose_ci = percentile_ci(
        &mut prose_vals,
        point.prose_similarity,
        alpha,
        n_iter,
        "bootstrap",
    );

    let mut per_layer = layer_ci_map_point(&point);
    per_layer.insert("prose".into(), prose_ci);
    per_layer.insert("overall".into(), overall_ci.clone());

    StyleSimilarityCi {
        estimate: point,
        overall: overall_ci,
        per_layer,
        n_iter,
        alpha,
        seed,
    }
}

fn layer_ci_map_point(point: &StyleSimilarity) -> HashMap<String, SimilarityCi> {
    let mut m = HashMap::new();
    m.insert("prose".into(), SimilarityCi::point(point.prose_similarity));
    m.insert(
        "rhythm".into(),
        SimilarityCi::point(point.rhythm_similarity),
    );
    m.insert(
        "character".into(),
        SimilarityCi::point(point.character_dynamics_similarity),
    );
    m.insert(
        "info".into(),
        SimilarityCi::point(point.information_flow_similarity),
    );
    m.insert(
        "causal".into(),
        SimilarityCi::point(point.causal_similarity),
    );
    m.insert(
        "temporal".into(),
        SimilarityCi::point(point.temporal_similarity),
    );
    m.insert(
        "topology".into(),
        SimilarityCi::point(point.topology_similarity),
    );
    m.insert("overall".into(), SimilarityCi::point(point.overall));
    m
}

fn percentile_ci(
    samples: &mut [f32],
    estimate: f32,
    alpha: f32,
    n_iter: usize,
    source: &str,
) -> SimilarityCi {
    if samples.is_empty() {
        return SimilarityCi::point(estimate);
    }
    samples.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let low_q = (alpha / 2.0).clamp(0.0, 1.0);
    let high_q = (1.0 - alpha / 2.0).clamp(0.0, 1.0);
    let low_idx = ((low_q * samples.len() as f32) as usize).min(samples.len() - 1);
    let high_idx = ((high_q * samples.len() as f32) as usize).min(samples.len() - 1);
    SimilarityCi {
        estimate,
        ci_low: samples[low_idx],
        ci_high: samples[high_idx],
        alpha,
        n_iter,
        resample_source: source.into(),
    }
}

// ─── Tests ──────────────────────────────────────────────────

#[cfg(test)]
#[path = "stylometry_stats_tests.rs"]
mod tests;
